### ISSUE TITLE
Can't send Nano from NanoVault if balance is 0.000001 NANO

### ISSUE THREAD

**Issue by egonm12** [cronoh/nanovault#10]
Whenever my wallet has a balance of 0.000001 NANO I can't send it to another wallet. If I try to send it I get the notice `From account does not have enough XRB`. 

While you can obviously see that the balance is there
![image](https://user-images.githubusercontent.com/20042349/36647036-d1b443c6-1a7f-11e8-9704-76e2a7a6013b.png)

**Comment by cronoh** [comment]
Sorry for the issues @egonm12 and thank you for reporting it.

This should now be fixed as referenced here https://github.com/cronoh/nanovault/issues/3#issuecomment-368735302

If your account balance is less than 1 nano, you might need to send 1 nano to that account, then use Send Max to send it all back out.  The reason being, transactions less than 1 nano are ignored by the server. Let me know if you run into any issues!
