### ISSUE TITLE
Address book should be locked

### ISSUE THREAD

**Issue by tanoabeleyra** [cronoh/nanovault#11]
Currently the address book doesn't get locked when you lock the wallet. I can see a security problem on that.

Lets say someone with access to my computer/phone opens NanoVault. My wallet is locked but if this person has free access to my address book then he could "change" one of my address (delete it, create a new one and set the same label). If after that I send some coins to this address just by looking at the label then my coins will be on another wallet (not the one I thought).

**Comment by cronoh** [comment]
Yeah I can definitely see that @tanoabeleyra thanks for pointing it out.  It is a pretty narrow attack vector in my opinion, but one worth keeping in mind.  The main trade off is that you will be unable to really view the address book or address book matches (On the account details page for example) while the wallet is locked.  But I think there may be some workarounds for that, and it still is probably a trade off worth making anyways.

I'll update here when I have it implemented.  Thanks for the feedback!

**Comment by tanoabeleyra** [comment]
Great!, thank  you for understanding my concern

**Comment by cronoh** [comment]
Finally working to clear out the long standing issues in here.  Please update if you feel this is still a problem!
