### ISSUE TITLE
Integrating POW in-browser

### ISSUE THREAD

**Issue by HostFat** [cronoh/nanovault#12]
Can you add integration for in-browser POW for both sending/receiving blocks?

Switchable on/off

https://github.com/numtel/node-raiblocks-pow
https://github.com/jaimehgb/RaiBlocksWebAssemblyPoW
https://github.com/numtel/nano-webgl-pow

**Comment by cronoh** [comment]
@HostFat Yes definitely, it is number one on the list at the moment - working on it right now actually, so expect it here in the next day or so.  I'll update this when it is implemented.  Thanks for the feedback!

**Comment by termhn** [comment]
See this PR: https://github.com/jaimehgb/RaiWalletV2/pull/8 (https://link.getmailspring.com/link/local-27b4976e-cb18-v1.1.4-22d9f20d@Rocket/0?redirect=https%3A%2F%2Fgithub.com%2Fjaimehgb%2FRaiWalletV2%2Fpull%2F8&recipient=reply%2B000d8b9f65c45b47fed08967385a120998b946064adfc23992cf0000000116aca27f92a169ce11e904db%40reply.github.com) for reference on also integrating @numtel's WebGL accelerated POW algorithm

**Comment by cronoh** [comment]
@termhn I'll give it a look thanks! I'm going to try and get all of the options available implemented and then have it use the fastest supported one by the browser, falling back to others - if possible.  I'll let you know when I have an update.

**Comment by cronoh** [comment]
Okay after decent amount of testing, I think I have the first two client-side Proof of Work options working here https://github.com/cronoh/nanovault/commit/2ecaa984f857cfb9b56f8cc0a141348a3cb22b31.  You can configure which type of PoW is used in your App Settings.  Until I have more testing on mobile for CPU, the 'Best Option Available' selection uses WebGL, then the server.  For testing the CPU option right now, you need to manually select the client side CPU option in the settings.

Please test it out and let me know of any issues you run in to!

**Comment by HostFat** [comment]
Great, thank you! :)

**Comment by HostFat** [comment]
It isn't completely clear that the user has to unlock the wallet to do the POW and receive the XRB.

**Comment by cronoh** [comment]
@HostFat Yeah I agree it isn't completely clear, let me see what I can do to make it more obvious.  Maybe I will make the warning notification stay up that tells you to unlock the wallet to receive the transaction.

**Comment by cronoh** [comment]
I think I have solved most issues with the client side PoW now - please open a new issue if you run into any specific problems!
