### ISSUE TITLE
Phone freezes

### ISSUE THREAD

**Issue by tanoabeleyra** [cronoh/nanovault#15]
My phone started to freeze when opening the webpage, it wasn't happening few days ago. Anyone else with this problem?

**Comment by giltotherescue** [comment]
Could it be the new addition of PoW?

**Comment by cronoh** [comment]
I recently added client side PoW, but just adjusted the way it is loading the libraries, which should hopefully help.  Let me know if it is still happening, and if so, any more details you can provide (Is it just a white screen for a while, or does the app load but gets frozen/starts to make your phone slow?)

**Comment by tanoabeleyra** [comment]
Sorry for not being more expressive earlier today.

I have a Blu R1 HD running Android 6.0 Marshmallow. On Chrome, as soon as it reaches the homepage the entire system starts lagging a lot and the only way to "fix" it is by killing the browser.

It doesn't happen on Firefox, but I guess PoW isn't working because a popup says "Unable to generate work for ... using clientWebGL".

Let me know if you need some more information.

**Comment by cronoh** [comment]
@tanoabeleyra Thanks for the details that helps a lot, I just deployed some changes which defaults the PoW to use the server when 'Use Best Available' is selected, which I'm hoping should resolve the issue.    If you have any trouble, make sure your PoW Source option is set to Best available or NanoVault Server in your App Settings.  Please give it a try and let me know if it works better for you.  Thanks!

**Comment by tanoabeleyra** [comment]
It's working fine again, thank you. Keep up the good work!
