### ISSUE TITLE
Lock Sidebar

### ISSUE THREAD

**Issue by Staterkid** [cronoh/nanovault#20]
Only a minor UI issue: If you scroll down in "App Settings" the sidebar on the left hand side scrolls down as well. Therefore you have to scroll up again to make the Sidebar visible again and to access the menu.

**Comment by cronoh** [comment]
Ah yeah good catch @Staterkid - I had been using it so long with a big screen I hardly noticed.  I added a fix in https://github.com/cronoh/nanovault/commit/4421e3481625f382346619d40f834278942fe0d4 which should now lock the main content area to the height of your browser window.  Let me know if this fixes it for you!
