### ISSUE TITLE
Remove Account label

### ISSUE THREAD

**Issue by Staterkid** [cronoh/nanovault#21]
1. If you want to edit an account label the red X might be a bit misleading. It works as "cancel" or "go back", I would have expected to clear the label. However, I see the point to have "cancel" or "go back" button.
2. To remove most user will delete labels in the Adressbock section. It is also possible to edit a label in the "account details" view and to save a blank label. This is equal to deleting the label. So for so good, just have a look at the pop-up message. I am not a native speaker, but this does look odd.

<img width="309" alt="screen shot 2018-03-04 at 16 07 36" src="https://user-images.githubusercontent.com/36902709/36947003-52959936-1fc6-11e8-88ee-fb72126a783a.png">

**Comment by giltotherescue** [comment]
I also noticed #1 when I accidentally mis-labeled a hash and tried to
remove the label.

**Comment by cronoh** [comment]
Thanks for the feedback @Staterkid and @giltotherescue, I have added some changes in https://github.com/cronoh/nanovault/commit/0fca468c67d63edc1c0a7239a241d60c606d9c56 that puts tooltips on those icons to make their actions more clear, and should fix the issue with the notification as well.  

Let me know if any other changes need to be made, but going to mark as closed for now.
