### ISSUE TITLE
Choose the remote node

### ISSUE THREAD

**Issue by HostFat** [cronoh/nanovault#22]
Is it possible to connect to a personal node instead of yours?

If yes, is it possible to add an easy settings on the interface?

**Comment by cronoh** [comment]
It is not possible right now, but something I definitely want to add in the future.  I've added it onto the road map here https://github.com/cronoh/nanovault/wiki/Road-Map - thanks @HostFat!

**Comment by mihaifm** [comment]
If I understand correctly, you cannot use your own node with this wallet?

This is a very important feature, I'm not sure why this issue is closed.
The wallet is not going to get better adoption unless people can use their own node with it.
