### ISSUE TITLE
Add donation account to your github repo

### ISSUE THREAD

**Issue by hobbysome** [cronoh/nanovault#25]
Add this even on your gihub repo xrb_318syypnqcgdouy3p3ekckwmnmmyk5z3dpyq48phzndrmmspyqdqjymoo8hj

**Comment by cronoh** [comment]
@hobbysome Thank you for the interest in donating!  I've added the donation address into the GitHub repo in https://github.com/cronoh/nanovault/commit/4b6af9b5831c657b55bb39a088391b131ebdda76
