### ISSUE TITLE
Add representative change blocks

### ISSUE THREAD

**Issue by stefonarch** [cronoh/nanovault#27]
Will be a must in future, giving user the choice; not all will do that  so there should be a system for randomly assign them or similar...

**Comment by cronoh** [comment]
At the moment, you can change your representative at any time by going to the details page of your account and clicking the pencil icon.  In the future I do want to add better support for giving good default options to pick from, I have it here in our roadmap https://github.com/cronoh/nanovault/wiki/Road-Map#proposed-features - thanks for the feedback @stefonarch !

**Comment by stefonarch** [comment]
Ooops sorry I missed that pencil icon...

**Comment by cronoh** [comment]
Haha yeah sorry it isn't very clear that you can do that - I'll work on some better UI so its more obvious how to change your representative.

**Comment by stefonarch** [comment]
Keep in mind elder people: contrast and size matters when eye light fades....
