### ISSUE TITLE
Feature request:  offline mode

### ISSUE THREAD

**Issue by george-viaud** [cronoh/nanovault#28]
This would require two computers w/ an air-gap.  The hot machine would provide the connection to the network and the cold machine would have the seed and perform signing.

The hot machine would either generate the POW itself, or transmit the last block info to the cold machine via QR-code to the cold machine so it could produce the POW though it would be ideal if the POW could just be computed on the hot machine.

The cold machine would produce the signed TX/RX and send it to the hot machine via QR code.

This would be a pretty ideal setup for air-gaped cold wallet operations.

**Comment by termhn** [comment]
I've been wanting to set this up for a while actually! It's on my list but
on the back burner right now while I work on nano-rs...

I also think it would be really cool to have an image you could burn onto
an SD card, pop into a raspberry pi, and use that as your never-been-online
always airgapped computer to make a setup like this super easy.

**Comment by george-viaud** [comment]
Exactly the setup I'm looking for.  It's so hard with most currencies...  Even more-so with all the dependencies just to get things to run on a livecd machine (npm isn't even included with ubuntu) so then you're rolling your own distro.  Crazyness.

Anyhow, I'd love to help but I'm pretty clueless when it comes to Node though I'm more than happy to help with testing and anywhere else it makes sense.

Be well,
g

**Comment by ThunderFD** [comment]
the RasPi idea is great, would be a really cheap option for a super secure air-gapped computer! but I think you'd need to buy the camera add on for it.. or type in the latest frontier yourself haha :)

so export frontier on your phone, scan it with RasPi, generate new block
and then just scan from your phone running nanovault in the browser there.. like in the settings: import block via QRcode

it'd probably be easier to run this on an old airgapped phone or something

**Comment by cronoh** [comment]
This is a great idea but going to consider it currently out of the scope of what nanovault is meant to do - closing the issue but please open a new issue if you have ideas for improving the offline capabilities!
