### ISSUE TITLE
When offline,  v1.0.2 x86-64 AppImage results in blank white window

### ISSUE THREAD

**Issue by george-viaud** [cronoh/nanovault#29]
Perhaps a runtime flag or network detection timeout here would permit the app to open without a network connection (experimenting with offline use now - would like to generate addresses etc).

```
Checking for update
Error: Error: net::ERR_INTERNET_DISCONNECTED
```

Thank you

**Comment by termhn** [comment]
See #18, currently the app is pretty much just an alternative browser window that connects to the main site and displays it. I just resolved the merge conflicts so you should be able to do

```
$ git clone https://github.com/termhn/nanovault
$ cd nanovault
$ git checkout electron-local
$ yarn install
$ yarn build
$ yarn dist
```
To build a version that includes the source locally. It may not be 100% functional but most things should work.

**Comment by cronoh** [comment]
Thanks for finding this @george-viaud - Not only do we need to get the desktop wallet serving the wallet locally (Thanks @termhn!), but the auto updater is what actually threw the error, so it needs to be tweaked a little bit as well.  I will update here when this is fixed.

**Comment by george-viaud** [comment]
For what it's worth, 'auto' anything scares some people (me for example ;) )  It may be a good idea to prompt the user if an update is going to happen and let them decide against.  Thank you for all the effort and sharing!

**Comment by george-viaud** [comment]
@termhn thank you - I haven't tried this yet but will be sure to report back when I do.  Be well

**Comment by cronoh** [comment]
@george-viaud  The wallet is now serving locally and also has a fix for the auto updater when running offline as of v1.0.3 - please let me know if you run into the same issue!
