### ISSUE TITLE
New logo proposal.

### ISSUE THREAD

**Issue by hobbysome** [cronoh/nanovault#30]
This is an example of a possible new logo. I may follow different directions.
![nanovault](https://user-images.githubusercontent.com/34998919/37243065-e83241c2-2473-11e8-89db-a196b0ad5dd5.png)

**Comment by hobbysome** [comment]
![2](https://user-images.githubusercontent.com/34998919/37244091-1e161088-2484-11e8-9697-80013de58ea6.png)

**Comment by termhn** [comment]
I like the first one a lot but it doesn't really say "vault" to me... just that it's related to nano :P

**Comment by hobbysome** [comment]
Maybe this fits well @termhn 
![3](https://user-images.githubusercontent.com/34998919/37247108-75a3f00e-24b6-11e8-81bd-920c0e5bb579.png)

**Comment by hobbysome** [comment]
![3](https://user-images.githubusercontent.com/34998919/37247277-2094cab8-24b9-11e8-9585-2f0c8fc3445a.png)

**Comment by hobbysome** [comment]
![3](https://user-images.githubusercontent.com/34998919/37252760-3af0cfd8-2527-11e8-9668-1e8c86796cf3.png)

**Comment by hobbysome** [comment]
![3](https://user-images.githubusercontent.com/34998919/37252787-d5913406-2527-11e8-8863-d1e3f4bbcb2a.png)

**Comment by ThunderFD** [comment]
maybe try some colors of the official logo instead of this turquoise?
really like them tho, maybe include scaled down versions.. like favicon and app icon size in your next posts.
It's hard to judge if they're too detailed or not

**Comment by hobbysome** [comment]
![3](https://user-images.githubusercontent.com/34998919/37253034-727ff410-252c-11e8-9306-386acde6a556.png)

**Comment by hobbysome** [comment]
![3](https://user-images.githubusercontent.com/34998919/37253049-aeb6f488-252c-11e8-84f4-b9c0ba202f2d.png)

**Comment by hobbysome** [comment]
![3](https://user-images.githubusercontent.com/34998919/37334749-09d75cc8-26ad-11e8-8d30-c8436140f108.png)

**Comment by hobbysome** [comment]
![3](https://user-images.githubusercontent.com/34998919/37334956-9dd2685a-26ad-11e8-82ee-3b5112fe98f6.png)

**Comment by ThunderFD** [comment]
why orange though? 

<img src="http://cdn.discordapp.com/emojis/403682760176435200.png" style="width:64px;height:64px;">

**Comment by hobbysome** [comment]
If you look nano.co the nano logo is blue (top) and orange (bottom).

**Comment by ThunderFD** [comment]
ahh true!

I like the last one, without the outer orange fill it'd be nice, but then it wouldn't work on white backgrounds

maybe an inverted version of that

**Comment by hobbysome** [comment]
@ThunderFD this is the inverted version, with trasparency.
![3](https://user-images.githubusercontent.com/34998919/37344856-cb2d995a-26cb-11e8-9596-f761e1149228.png)

**Comment by hobbysome** [comment]
![3](https://user-images.githubusercontent.com/34998919/37345237-bdce1888-26cc-11e8-941e-f64c42714168.png)

**Comment by ThunderFD** [comment]
don't make the center transparent tho 😄 

anyway, I did a mockup in orange and blue, of what you'd see in browser
![nanovault_mockup](https://user-images.githubusercontent.com/17814079/37346609-096f1d7a-26d0-11e8-8598-8b643040f0b3.jpg)

**Comment by hobbysome** [comment]
I guess transparency looks good on android app and desktop app.
It's forced to be total white on iOS app.

**Comment by ThunderFD** [comment]
imo this logo is too delicate to use transparency on the inside, also it's by far less readable than what nanovault currently has.

that's one thing that I don't really like that much about the official logo too, it's not that readable when scaled down to favicon sizes

**Comment by hobbysome** [comment]
@ThunderFD This is the version white filled in the box
![3](https://user-images.githubusercontent.com/34998919/37369072-4f6f415a-2708-11e8-95b1-e487a12d6f2d.png)

**Comment by hobbysome** [comment]
![3](https://user-images.githubusercontent.com/34998919/37369710-316fa68e-270a-11e8-87c5-b3ff4df45e77.png)

**Comment by cronoh** [comment]
@hobbysome Wow those are some great logo ideas - thanks for all of the different concepts.  I really like the last one, the orange with the white just looks surprisingly good to me.  The one thing I am concerned about though is using the direct Nano logo.  It seems like we might have some IP issues doing that.  Do you have any other ideas for the center by chance?  Thanks for all your hard work!

**Comment by hobbysome** [comment]
This is an alternative versione without official logo: @cronoh 
![3](https://user-images.githubusercontent.com/34998919/37388197-c7a17920-275f-11e8-92ba-19d1fdf16bf1.png)

**Comment by hobbysome** [comment]
Also this more compact version:
![3](https://user-images.githubusercontent.com/34998919/37389649-6b503584-2765-11e8-8ea4-33f0ec51c408.png)

**Comment by hobbysome** [comment]
And this one:
![3](https://user-images.githubusercontent.com/34998919/37389988-a4cfe6be-2766-11e8-80cb-e801a4a9cfaf.png)

**Comment by hobbysome** [comment]
![3](https://user-images.githubusercontent.com/34998919/37390758-69a67c58-2769-11e8-9002-a8ae4ca31afe.png)

**Comment by hobbysome** [comment]
![3](https://user-images.githubusercontent.com/34998919/37401388-3130de80-2788-11e8-850f-84775e619cb3.png)

**Comment by hobbysome** [comment]
This is my favourite version @cronoh 
![3](https://user-images.githubusercontent.com/34998919/37514925-7f33f8ce-2909-11e8-8adc-61a96623eb2e.png)

**Comment by termhn** [comment]
I like that last one but with rounded edges on the outside as well. The compact versions look good.

**Comment by hobbysome** [comment]
Here it is
![3](https://user-images.githubusercontent.com/34998919/37534626-a77df596-2945-11e8-9da6-a364e68af0d9.png)

**Comment by pedfx** [comment]
I don't think IP could be a problem... but lol
![walkman-1](https://user-images.githubusercontent.com/12234380/37551039-ee3197f0-2976-11e8-9413-329b02b173be.jpg)

**Comment by cronoh** [comment]
Thank you @hobbysome for all of your awesome iterations on the logo!    I think I have decided on one to roll with for now, which is a combination of the color from https://github.com/cronoh/nanovault/issues/30#issuecomment-372070412 and the style of https://github.com/cronoh/nanovault/issues/30#issuecomment-372940129.  The orange looked great, but after messing around with it a bit, it didn't really match the application.  I think the combined result looks pretty good though!  

It has been deployed in v1.0.3 to desktop applications, and just requires a hard refresh on the web wallet.  I am going to close the issue for now, but please let me know what you think, and if it is not well received I will re-open the issue for more ideas.  Thank you everyone for all of the great feedback in here!
