### ISSUE TITLE
Add incoming link support

### ISSUE THREAD

**Issue by stefonarch** [cronoh/nanovault#34]
Links like` xrb:xrb_3rropjiqfxpmrrkooej4qtmm1pueu36f9ghinpho4esfdor8785a455d16nf `should  be handled by NanoVault,  opening directly  the compiled send tab after unlock.
Under linux adding 
`MimeType=x-scheme-handler/xrb;
`
in .desktop file works well - just the wallet will not hande it.
test: http://nanode21.cloud/link_xrb.htm

**Comment by cronoh** [comment]
@stefonarch Support for handling the `xrb:` protocol has now been added in v1.0.3 - please let me know if you run into any issues!
