### ISSUE TITLE
reordering address book

### ISSUE THREAD

**Issue by ThunderFD** [cronoh/nanovault#36]
I'd like to be able to reorder my address book by 
- clicking and dragging one of the contacts, and dropping it somewhere else
- or up/down buttons that show up on hover

**Comment by pedfx** [comment]
A search option for local names would be nice as well.

**Comment by cronoh** [comment]
@ThunderFD I have added in the ability to re-order the address book in https://github.com/cronoh/nanovault/commit/e2f5988c1bc19bc7cda9736219c7e6c23888fe34 which was deployed in v1.0.3.  To use it, hover over the label in your address book and drag/drop the handler icon to the position you want.  Once it seems to be working well in the address book, I plan to port the feature to the accounts page as well - thanks for the suggestion!  Let me know if you run into any issues.

@pedfx That is an interesting idea - do you have so many address book entries that it is necessary?  If you think it is needed, please open a new issue for it and I will add it into the list.  Going to close this issue for now though - thanks!

**Comment by ThunderFD** [comment]
oh sweet! works great! 🎉
