### ISSUE TITLE
Account balance not appearing

### ISSUE THREAD

**Issue by hobbysome** [cronoh/nanovault#37]
After importing seed, one account balance is not showed, but if I click on the account, the balance is showed correctly.

**Comment by pedfx** [comment]
It's because, before entering a seed, the website load randomly a new seed, so it probably is empty but if you are the most lucky person in the world you may see a balance before entering a seed lol.

**Comment by termhn** [comment]
> After importing seed, one account balance is not showed, but if I click on the account, the balance is showed correctly.

@hobbysome can you describe more carefully exactly the series of events that you took, what should have happened, and what actually happened? Thanks!

> It's because, before entering a seed, the website loads randomly a new seed, so it probably is empty but if you are the most lucky person in the world you may see a balance before entering a seed lol.

Hmm, I don't think that's what's going on--someone else in the discord also reported an issue that sounded similar so I think there might be something going on. Perhaps we're not reloading account balances at some point we should be.

**Comment by cronoh** [comment]
@hobbysome Any update on this issue?

**Comment by hobbysome** [comment]
@cronoh Reloading screen seems solved now.
