### ISSUE TITLE
Not yet compatible with nanode.co alias

### ISSUE THREAD

**Issue by pedfx** [cronoh/nanovault#38]
hello

This week nanowallet.io just got the nanode.co alias to be used as way to enter an account address when sending transactions.

In this image you can see in the account to send from: the grey observation "(HODL)" that's the local name of this address. The next textbox is filled with "pizza" that is a nanode.co alias, and just by typing this alias it entered the full address for me.

 
<img width="604" alt="captura de tela 2018-03-16 as 23 03 52" src="https://user-images.githubusercontent.com/12234380/37550585-6faf6f54-296e-11e8-84a8-7ca1617db5a3.png">

In this other image you can how the alias look on the main page, as the grey being the local name and the red with an "@" the nanode.co alias

<img width="511" alt="captura de tela 2018-03-16 as 23 46 35" src="https://user-images.githubusercontent.com/12234380/37550890-91f885a4-2974-11e8-8051-9dee7ffcdcb0.png">

That would be super helpful, as today the nanovault.io is the best option for a mobile wallet (even smother than the devs mobile wallet right now), so adding this option to use nanode.co alias as a way to retrieve addressed

**Comment by termhn** [comment]
See https://github.com/cronoh/nanovault/issues/26

**Comment by pedfx** [comment]
Oh that's new about canoe @termhn. 

I recently received an alert from canoe to never use their app again because of security reasons, so they disabled it to download. I just went to their website right now and 5th of march was the last day they talked about releasing a beta, still unavailable for download

<img width="914" alt="captura de tela 2018-03-17 as 01 57 48" src="https://user-images.githubusercontent.com/12234380/37551802-a0218a24-2986-11e8-8180-ea68ee800a5d.png">


But instead of an oficial announcement - as this is a decentralized currency and this "dev only decision" shouldn't even exist (as even the creator, Colin, says it too) - it could be an option to make both available with a select option - nanode/canoe - before entering the alias and the wallet showing below as "xrb_1111..." so people can verify it before sending. 
That way it can just implement every new api, and people can use just by selecting which one. (perhaps for a future change, one can select on the settings, witch services will appear as an alias option in the selection box)

Just giving my 2cents, because the Nano Brazilian group just discovered this option recently and since then 3 influencers made videos/articles about it. - they say it's as easy as sending an email, and I can't disagree

**Comment by termhn** [comment]
It is easy for the user, but we don't want to include something that could potentially compromise users' security, even if it will make things more convenient. We definitely want to include aliases at some point, but only once a standard is created with consensus by the community that we deem sufficiently secure. Here's a comment I've written about these aliases before (both nanode and canoe):

> This is inherently a centralized security model, which goes against everything that makes decentralized security models like cryptocurrencies great. One entity (nanode) has the power to divert funds (whether on purpose or because they get hacked) to whatever account they want based on their api/database lookup." That said, I don't hate nanode aliases (I own one myself) but I think it should be an entirely opt-in thing rather than included in wallets for that reason

I can't speak for @cronoh, but I think he shares a similar view

**Comment by cronoh** [comment]
Thanks for the feedback @pedfx!  As @termhn has mentioned and as is referenced in #26, we will be waiting on adding alias support until there is a more clear stance taken by the core Nano team.  I agree it is a very useful feature though, and we will definitely be adding it in when its safe for everyone to use.
