### ISSUE TITLE
Online|offline indicator for representative

### ISSUE THREAD

**Issue by fallerOfFalls** [cronoh/nanovault#39]
It would be nice if beside each representative address, there was some indication of whether your representative is online and voting. That way you'll be prompted to consider changing rep if it's offline, and otherwise, feel reassured.

**Comment by cronoh** [comment]
Hey @fallerOfFalls thanks for the suggestion.  I agree that would be a good feature to have, and would fit well into the planned improvements to the representatives UI.  I looked into it a bit earlier, and it seems it will require pulling the votes database from the Nano node to accomplish, along with a server to hold the status of each representative.  Not that hard to pull off, but a small divergence from the current focus.  I'm going to mark it as a future enhancement, and will add it in as soon as the time is right.

**Comment by cronoh** [comment]
@fallerOfFalls I have added in a new representative overview page which shows you the online status as well as a few other details about your representatives (Settings > Representatives).  You can then easily change the representative on your account(s) and manage the Representative List, which functions like your address book.  It is currently live on the web wallet and will be moved to the desktop wallet in the next version as long as it is bug free, so please let me know if it is working well for you.  Thanks!
