### ISSUE TITLE
"Missing" accounts

### ISSUE THREAD

**Issue by tanoabeleyra** [cronoh/nanovault#4]
I found another UX problem similar to #2.

I have two accounts, the main one and a secondary which I manually created with the _Create new account_ button. Every time I lock and unlock my wallet this second account disappears. The account is already opened (sent a transaction from the main one) and it also has balance on it.
To make it visible again I have to click again on _"Create new account"_ which is a bit misleading.

**Comment by tanoabeleyra** [comment]
After thinking about it a bit more it seems to me that this problem is **totally** related to #2, you need to click _Create new account_ for the first account to appear, click it again for the second one, and so on.
Let me know if I should close this issue, fixing #2 should fix this.

**Comment by cronoh** [comment]
Hey @tanoabeleyra Thanks for reporting it - it does sound like the same issue, which is that when you load the application with a locked wallet, after unlocking, it does not properly reload all of your accounts (Causing you to have to recreate them).  If you can confirm that locking and unlocking without a reload works fine, but reloading after locking causes the bug, then I think we are safe to mark it as a duplicate, and should have a fix in soon.

**Comment by cronoh** [comment]
A fix for this should now be live as referenced in issue #2 Here https://github.com/cronoh/nanovault/issues/2#issuecomment-366864898 - Let me know if the bug is sill there for you.
