### ISSUE TITLE
Logo proposals.

### ISSUE THREAD

**Issue by ghost** [cronoh/nanovault#40]
Hi @cronoh !
I prefer the full background version (squared one). With a more lighter blue color, so it looks more young and UI friendly.

(square borders are necessary on iOS due to its policy for iOS app (no transparency), I guess borders will be automatically rounded when uploaded for iOS.

I attach the generated png and the svg version (zip).

Let me know.

![3](https://user-images.githubusercontent.com/34998919/37759372-b010a272-2db3-11e8-91d2-aba711c57c48.png)

[3.zip](https://github.com/cronoh/nanovault/files/1836669/3.zip)

**Comment by cronoh** [comment]
@hobbysome Would you use this square (blue outside) version for just the iOS application?  Or for all places?  It seems to me like for the favicon on the web wallet, the current version is better since I think the N will become distorted if any smaller.  Thanks again for your contributions 👍

**Comment by hobbysome** [comment]
I would use it for all version. I upload the center aligned version now.

**Comment by hobbysome** [comment]
![3](https://user-images.githubusercontent.com/34998919/37954852-4dd6aac8-31a7-11e8-9e7e-94c2f34d4d40.png)
[3.zip](https://github.com/cronoh/nanovault/files/1850982/3.zip)
