### ISSUE TITLE
Send a $$ value option

### ISSUE THREAD

**Issue by sixplants** [cronoh/nanovault#42]
Paying for stuff in $$ rather then Nano.   Perhaps one day the world will talk Nano rather then $$, but it's not quite ready yet.  So,it would be nice to have a send $$ function rather then trying to work out the current exchange  Nano / $$  rate.

**Comment by cronoh** [comment]
Thanks for the suggestion @sixplants, I agree it should be in there, and shouldn't be too difficult to add either.  Let me try see if I can get the UI looking right, and I'll update here with the results.

**Comment by cronoh** [comment]
@sixplants I have added in support for sending in fiat balances in https://github.com/cronoh/nanovault/commit/5d5f37e1b1517ca0c71b6edeea5810d7353105b3 which has been deployed to the web wallet (Coming soon to the desktop wallets if it is bug free). Give it a try and let me know if it is working how you expected or if it needs any improvements.  The UI is a little rough, so I am definitely open to better ideas on how to display it.
