### ISSUE TITLE
account viewer/explorer not showing pending deposits

### ISSUE THREAD

**Issue by fallerOfFalls** [cronoh/nanovault#43]
I know there's a pending deposit there, because it shows on nanode block explorer.

This is for addresses in the address book, not the account you're currently logged in with.

**Comment by cronoh** [comment]
@fallerOfFalls Ah okay yeah that will happen for accounts which have not yet been opened at all.  I will add in another call to try and check for pending on accounts which don't have an open block yet.  I'll update here when it's added.

**Comment by cronoh** [comment]
@fallerOfFalls I have added support for this in https://github.com/cronoh/nanovault/commit/0d06d8e69d6397bbab63ca52026bccc34fd5d4fb which also includes showing pending transactions in the history list below, for all accounts.  It is currently deployed to the web wallet, and will go to the desktop wallets in the next release.  Let me know if this works for you!

**Comment by fallerOfFalls** [comment]
Sounds great!
