### ISSUE TITLE
UX: when no password set, unable to send, no explanation

### ISSUE THREAD

**Issue by fallerOfFalls** [cronoh/nanovault#44]
says "generating proof of work" and then just carries on apparently trying to send forever.

**Comment by cronoh** [comment]
Sorry for the issues - Which PoW method do you have selected in your App Settings?  Can you try changing it to a different one and let me know if that works?  If the 'NanoVault Server' option does not work, try also using the 'Clear Work Cache' button on the bottom of the App Settings.  Please report back with whatever you find @fallerOfFalls, thanks!

**Comment by fallerOfFalls** [comment]
Unfortunately I have no idea how it got into the no password set state, so I wouldn't know how to reproduce. However, before I realised that was the problem, I did try multiple PoW settings including your server, and i tried deleting the work cache. All had no effect.

As soon as I set a password, everything worked as normal.

The problem seems to be that where it would usually prompt for a password, it just doesn't do anything, if no password is set.
