### ISSUE TITLE
Rep went offline, unable to change rep now. Balance shows zero.

### ISSUE THREAD

**Issue by fonso2** [cronoh/nanovault#46]
https://www.reddit.com/r/nanocurrency/comments/8bvv0w/nanovault_showing_zero_balance_nanode_says/?st=jfxcfe7r&sh=f8c836fc

Short of downloading the full wallet, syncing the node, and then changing reps, is there any way that we can still change representatives in this state?

**Comment by cronoh** [comment]
Hey @fonso2 thanks for reporting this - it looks like the Nano node crashed for some reason, which caused all of the requests to fail.  I have restarted it so it should be working again if you refresh.  Let me know if it is fixed for you.

**Comment by fonso2** [comment]
Thanks cronoh!  All good on my end now :)
