### ISSUE TITLE
Improve UX when Node API cannot be reached

### ISSUE THREAD

**Issue by termhn** [cronoh/nanovault#48]
We should have a notification and probably a persistent UI element that notifies a user when the Node cannot be reached properly, and have the balance display something like `--` with a note about connectivity issues rather than just having 0. Several users have been a bit freaked out when this has happened, one being #47 and a few in the Discord as well.

**Comment by cronoh** [comment]
Added tracking of the node status in https://github.com/cronoh/nanovault/commit/73cb527a31d14fcdee1ed4255a666a37838bc8fc which will show a notification and warning on the navigation when the node is offline.  Hopefully this should cover it!
