### ISSUE TITLE
Ledger Nano S support on the desktop version

### ISSUE THREAD

**Issue by fallerOfFalls** [cronoh/nanovault#49]
Will the desktop app support Ledger Nano S, or only the webwallet with chrome?

**Comment by cronoh** [comment]
@fallerOfFalls Yes definitely, Ledger support will be coming to the desktop applications in the next release, as soon as I have fixed any small remaining issues (So hopefully in a day or two).

**Comment by novytschogg** [comment]
hey same question here. the 1.0.4 wallet does not have any ledger nano s scroll down option, so there will be some new desptop wallet 1.0.5 which will support this, right?

the chromevault works great love it. ledger supported.:)

**Comment by cronoh** [comment]
Yeah @novytschogg - the next version (1.0.5) will have support for the Ledger.  Was on vacation so missed my planned date for release, but expect it this week for sure!

**Comment by novytschogg** [comment]
cronoh thanks a lot, you are the man! hope you returned well recovered :+1: 

many greetings!

**Comment by jawereq** [comment]
@cronoh, I just wanted to say I'm really looking forward to this feature.  Having ledger support in a standalone, open source desktop wallet will be great peace of mind.  Thanks for what you do.  NanoVault rules!

**Comment by cronoh** [comment]
Long overdue, but this feature is now ready.  Please let me know if it is working well for you!

**Comment by novytschogg** [comment]
thanks will have a look on it... thanks a lot for your dev skills.

Am Do., 31. Jan. 2019 um 08:43 Uhr schrieb Andrew Steele <
notifications@github.com>:

**Comment by cronoh** [comment]
I am going to close this issue for now.  Please open a new issue if you have any issues with the Ledger - thanks!

**Comment by jawereq** [comment]
I'm running it with no problems so far.  Very nice work!
