### ISSUE TITLE
Wallet does not lock on close

### ISSUE THREAD

**Issue by stefonarch** [cronoh/nanovault#5]
Using AppImage, on closing it does not lock the wallet. Security risk.

**Comment by cronoh** [comment]
Understood.  I will be looking into adding two options in the near future: 
1. Auto-lock on window close
2. Auto-lock on inactivity after x minutes.

I will leave this as an open issue until both of those are implemented.  Thanks for the feedback!

**Comment by cronoh** [comment]
Both of these options have been added in https://github.com/cronoh/nanovault/commit/c89596c4f3d325ec04649bbbf46546c04d82a1dc and should be live.  Let me know if you experience any issues!

**Comment by stefonarch** [comment]
Works as expected, thanks!
