### ISSUE TITLE
ISSUE OPENING NANO APP FROM BTC WALLET

### ISSUE THREAD

**Issue by thesonofja** [cronoh/nanovault#50]
Hello I was directed to add a support issue here from the ledger support team. When I open the LEDGER BTC wallet on my desktop and then open the recently added nano crypto app from my ledger nothing happens at all. It works fine for all other apps and they open perfectly. I was told by ledger support team that most likely there is some problem with my operating system? The computer Im using is only 1 month old and Im using windows 7. 

The firmware on my ledger has been confirmed to be updated to the latest version and I also experimented saying yes and no to browser support in the nano app. Still the nano wallet wont open using the BTC wallet.

Please advise asap...

Regards,

J

**Comment by cronoh** [comment]
Hey there @thesonofja, you need to use the NanoVault web wallet to interact with the Nano app on your Ledger.  You can find the full guide for how to use them together here: http://blog.nanovault.io/guides/use-your-ledger-device-with-nanovault/ - Let me know if you still have any issues after reading that.

**Comment by thesonofja** [comment]
Ok Cronoh so yeah had some pretty big inconvenient issues come up with this whole process indeed...

I already had the nano wallet installed on my desktop that had my coins on there and balance etc...before I even contacted you regarding this issue.

I followed your link and finally found where the IMPORT EXISTING WALLET button was but unfortunately there was no Leger Nano there in the dropdown as an option. Only Nano Seed, Nano Mnemomic phrase, and Nano Vault Wallet file were the options...

In any case, I then think I accidentally clicked on create a new wallet by accident and then my previous Nano coin balance and dollar amount went away!!! WTF? So, I thought I could recover it by entering the backup seed or Mnemomic phrase I wrote down when creating the original wallet in the Import existing wallet area to recover it but it did not work at all! It said it was not recognized. Was this because I was already in the new wallet area? That is what Im intuiting. So how do I see my old wallet balance?

Please kindly advise ASAP how to deal with this issue and use my ledger from now on to access my coins...

Regards,

J

**Comment by cronoh** [comment]
@thesonofja If you are on the create new wallet page, there is a warning at the top to ensure you have your seed backed up before continuing.  If you have your seed from that wallet, you should be able to reload the accounts on it.  Import it as an existing wallet and if needed, press 'Add New Account' a few times, to see if it reloads your balances.  To use your ledger device, follow the guide above, and maybe do it in an incognito window, so that your normal vault wallet stays intact.  Jump onto our discord server if you are still having issues and I'll try and help you out!

**Comment by thesonofja** [comment]
Brother I dont think you read my email in its entirety. I clearly told you
that in the drop down menu there is absolutely no option at all for ledger.
Only Nano seed, Nano Mnemonic phrase, and Nano Vault Wallet file.

Please let me know how to proceed with only these options...

Regards,

J

**Comment by cronoh** [comment]
@thesonofja Currently the Ledger option is only available when using the web wallet (https://nanovault.io) not on the desktop wallets.  It will be coming to the desktop wallets soon, sorry for the confusion!

**Comment by thesonofja** [comment]
Ok well how do I integrate the web wallet with my current desktop wallet?
Can I import it from the desktop to web and then back to desktop later?
When will it be integrated with the desktop by the way? Lastly isnt the
desktop wallet more secure than a web wallet? If so I may just wait for
integration to take no chances...

Thank you...

J

**Comment by thesonofja** [comment]
Ok well how do I integrate the web wallet with my current desktop wallet?
Can I import it from the desktop to web and then back to desktop later?
When will it be integrated with the desktop by the way? Lastly isnt the
desktop wallet more secure than a web wallet? If so I may just wait for
integration to take no chances...

Thank you...

**Comment by thesonofja** [comment]
Are you going to respond? Im sorry for all the questions! Doing my best to
get clarity here so I can move forward. Thank you Andrew!

Regards,

J

**Comment by termhn** [comment]
If you're using a ledger hardware wallet, then the ledger device itself is your "wallet." The web and desktop "wallets" for NanoVault are simply user interfaces to interact with your ledger device in a user friendly manner. You can switch back and forth between the web and desktop interface at will (once the desktop version is updated with ledger support in the future).

The desktop wallet is only very slightly more secure than the web wallet, and if you're using a hardware wallet, then the whole point of having said device is that it doesn't matter whether the computer or software you're using it with is compromised or not, it can't harm you. So there's no (known) disadvantage or insecurity to using the web wallet for your use case.

**Comment by thesonofja** [comment]
Hello as you can see we have spoke before. I am having some issues with my
Nano desktop wallet and need some help. It seems there is no security
because even though it is locked when I click on it it opens up without a
password. So if my computer gets stolen its seems its free money for
someone as long as they have a Nano address to send to...

Should I use the web wallet instead now with my ledger if I cant fix this
issue?

I also would like to know when the Desktop wallet will be supported by the
Ledger Nano S? Obviously there will be more security for me that way!

Regards,

Jason

**Comment by cronoh** [comment]
Hi there @thesonofja, it would sound to me like your password got reset on your wallet to a blank password maybe.  Once you have the wallet unlocked, go to Settings > Manage Wallet and change the password on the wallet to something new.  If your computer gets stolen, this would be the only thing protecting your Nano if they could also login to your operating system and such.  It is recommended to use a good password if you are worried your computer might get stolen.


Support for the Ledger on the desktop wallets should be sometime soon, i have some of the basics working in my development environment, but it might be a week or so still before I can get it finished.

**Comment by thesonofja** [comment]
OK so I just changed the password and the same issue is occurring. I can
just open the wallet without it asking for a password and then coins can
easily be sent or received just like before. Im confused here. I dont see
how this wallet is secure.

Again, I have a desktop wallet...

Regards,

Jason

**Comment by thesonofja** [comment]
Andrew I responded with the issue I am having and still no response. Can
you please get additional help for me regarding this issue if you cant help?

Again, here is a copy of what I wrote to you in response...

"OK so I just changed the password and the same issue is occurring. I can
just open the wallet without it asking for a password and then coins can
easily be sent or received just like before. Im confused here. I dont see
how this wallet is secure.

Again, I have a desktop wallet...

Regards,

Jason"

**Comment by cronoh** [comment]
@thesonofja Sorry for not having a solution for you before :( I am going to close this issue but please open a new one if you are still having problems and I will help you out however I can.

**Comment by Jon1325** [comment]
I was left in shock and depression after being deceived by bitfinex investment where I lost about 395,000 USDT of my entire life savings which I was planning to get a company after my retirement as life investment for my kids but this nitwits stole it from me. However after weeks of my depression I finally met REMOTESPYTECH (at) gmailc0m through a close friend referral and he got back all my stolen assets instantly without hassle or hidden fees. He’s the only real deal out here as I’ve tried many but they failed. He was my final and last hope. I’m grateful Mr Romero delivered. Get in touch with him now!!!!

Email: REMOTESPYTECH (at) GMAILC0M 

whatsapp: +1 (352) 870-0844

Tremendous Service
