### ISSUE TITLE
Unable to connect to the Nano node, your balances may be inaccurate!

### ISSUE THREAD

**Issue by owlfarm1** [cronoh/nanovault#51]
Hello,
Using the ledger nano s with nanovault. Everything seems fine except I get an error message at the bottom stating:
' Unable to connect to the Nano node, your balances may be inaccurate!' -- how do I sort out this issue?
Thank you - Cheers.

**Comment by cronoh** [comment]
@owlfarm1 Does this issue persist for you if you refresh the page?  That error shows up when it cannot make a connection to our cloud Nodes, but we haven't been having any outages lately.  Let me know if it is still happening, thanks!

**Comment by ninjavz** [comment]
I am having the same problem but without Ledger. Using Nanovault Appimage on Ubuntu. It says: "attemting to connecto to nano node" forever (circle spinning).

**Comment by nicStuff** [comment]
@cronoh Yes it persists: after refreshing the page, I reconnect to the nano, then after a bit the message appears. It's odd because sometimes nanovault did show me the pending deposits (and then the approval didn't work, but that's another issue).

**Comment by CharlieL83** [comment]
@cronoh Hi and same problem here .. and I also have the same problem with pending deposits and not showing my balance
Unable to connect to the Nano node, your balances may be inaccurate!
connecting with chrome and ledger nano s
Thanks!

**Comment by nicStuff** [comment]
@cronoh Now all worked flawlessly (seeing pending deposit, confirming it, sending nano): it looks like it was a temporary issue.

**Comment by spinningdolphins** [comment]
I'm trying to resolve this issue where it says Unable to connect to the Nano node, your balances may be inaccurate! Not sure what to do, I've tried connecting with Chrome and Ledger Nano S and Brave and Ledger Nano S and turning off the ad blocker like it recommended. Hopefully, this is a temporary issue but if anyone knows something more I'd greatly appreciated your ideas. Thank you!
