### ISSUE TITLE
Import seed from Ledger Nano show wrong account

### ISSUE THREAD

**Issue by Joohansson** [cronoh/nanovault#52]
I connected a new Ledger Nano S to nanovault and I was given an account. I started to send to that account (and verified all transactions with the ledger button). To verify I closed browser (with wallet storage set to "none" in settings), opened again and connected ledger and everything was fine.

Now one week later I almost got a heart attack when I opened up a fresh browser and imported my ledger and it showed a different account and zero balance! Back from my head I remember reading somewhere that you need to hit "Add new account" and I did that. The old account was generated with correct balance. Now I have to do this every time I connect my ledger. Is this safe? What if that account is not generated next time and I get a third account? I'm thinking of moving my nano to the default account instead but will it happen again, and why?

I'm not 100% sure but I think it failed to give me an account first time I connected my ledger and I had to press "add new account". I know I only had 1 account when I started to use it but this might have "delayed" the default account somehow and it first appeared now and the account I thought was the default one is now number 2.

**Comment by cronoh** [comment]
Sorry for missing this @Joohansson - since it has been so long I am going to assume you have solved the issue.  If you still need any help here, please reply and I will re-open the issue.  Thanks!
