### ISSUE TITLE
Ledger marked "disconnected" after each confirmation on the Ledger

### ISSUE THREAD

**Issue by loupiote** [cronoh/nanovault#53]
Everytime I click the button on my ledger to confirm a receive, the Ledger disconnects from nanovault.  
(I currently have auto-receive = No)
According to roosma, it's an issue with nanovault.  here is what he says:
"Technically the U2F protocol used for communication between the browser and the device is stateless. There's no way to tell if the device is still connected unless you try to run some commands on it.

So if NanoVault just claims that the device is disconnected but when you try to do things it still works, then it's just NanoVault illusion breaking down (the connected/disconnected state illusion) If the app on Ledger quits or it freezes Ledger (so that you need to unplug and replug it), then its my issue."

So yes, since the app is still running on the Ledger device, and it gets marked "connected" when i click "reload ledger status" on nanovault, it seems that it's an issue with nanovault.io

**Comment by cronoh** [comment]
Hey there @loupiote - I am closing up old issues that may not apply any more, if you are still having this problem please reply here or open a new issue, and I will do my best to find the problem.
