### ISSUE TITLE
Support for 'nano_' address prefix

### ISSUE THREAD

**Issue by pRizz** [cronoh/nanovault#55]
Currently, when sending, the app thinks this is an invalid address.

The official wallet is able to parse this address:
https://github.com/nanocurrency/raiblocks/blob/master/rai/lib/numbers.cpp#L82

**Comment by plattfuss333** [comment]
Any update on this? Just took me 15min to figure out why it kept saying "unable to send: invalid NANO account"

**Comment by cronoh** [comment]
Thanks @termhn - I'll be doing some testing with your PR to see if it covers everything needed.  I'll update here when support is officially ready.
