### ISSUE TITLE
I have not received the funds

### ISSUE THREAD

**Issue by josevilanova** [cronoh/nanovault#57]
Hello,

Yesterday I sent 33.99 Nano from Binance to NanoVault. From Binance they confirm to me that everything is correct and the transaction has been completed.

But I still have not received the funds, it says "Unpocketed Transactions".

Please, can you help me?

https://www.nanode.co/block/95E1655BDEB0DD510BA9B500796CC76C00E60E112ED701C77D3F0E2DC2B86FCB         (the operation)

https://www.nanode.co/account/xrb_1rdrxuzorhod5k6esa3oxfuzths6ir9exuiatb4gktsywh78jiepk1amrym6 
      (where I sent it)

Thank you,

**Comment by sidharthramesh** [comment]
I have the same issue on my account. A friend sent me 1 Nano from Binance. It shows up on the block explorers, but I can't see it in nanovault. I am using a Ledger S Nano with auto-receive turned on.

https://nano.meltingice.net/explorer/account/xrb_141erkwakw9ykdau15i1njn946qnekihsqw9ucqe6pwo43fjxx5q9hy3kc8c/history

**Comment by cronoh** [comment]
I am pretty sure the issue was related to the Node being out of sync with the network at the time, and everything is likely resolved.  If you are still having any problem, please reply here or open a new issue and I will see what I can do to help!
