### ISSUE TITLE
change the default representative for new wallets

### ISSUE THREAD

**Issue by ThunderFD** [cronoh/nanovault#6]
either run a nanovault rep,
or pick some of the trusted known reps (apart from the devs and exchanges)

then pick one of them at random when creating open blocks

**Comment by cronoh** [comment]
Sounds good, I will default everyone to the NanoVault rep and update this when deployed!

**Comment by cronoh** [comment]
@ThunderFD This has now been added in https://github.com/cronoh/nanovault/commit/ab2d8151e3f62a7f72c12aa2d58c04a4f824ec35.  The default representative on open blocks will be set to the Official NanoVault Representative: `xrb_3rw4un6ys57hrb39sy1qx8qy5wukst1iiponztrz9qiz6qqa55kxzx4491or` 

Thanks for the feedback!
