### ISSUE TITLE
Warn user when importing wallet if existing wallet already setup

### ISSUE THREAD

**Issue by jcraigk** [cronoh/nanovault#63]
Currently if a user imports a new wallet but had already been using another wallet, the system does not warn the user that it cannot handle multiple wallets at the same time.  If the user had not backed up the previous wallet's seed, it would be lost forever.  Adding a confirmation with information about this would be helpful during the import process.

**Comment by dVoooo** [comment]
There is a big warning message or did i missed something?

![image](https://user-images.githubusercontent.com/43923199/50585560-e8ba5980-0e75-11e9-97a8-1fdf4e2c5319.png)

**Comment by jcraigk** [comment]
See specifically the last sentence of my original post and note the `confirmation` part, meaning a popup with `Cancel` or `OK` options that would appear before proceeding with replacement of existing wallet.  This pattern is standard in modern interfaces before proceeding with a very destructive action.

The warning in the screenshot you provided is in small text along with a lot of other small text on the screen.  It is red but many folks will not be able to perceive that.

I would suggest the following wording on the confirmation: "You are about to import a new wallet, which will remove your existing wallet!  If you do not have your wallet seed backed up, all of your funds within it (<insert total here>) will be lost forever!  Are you sure you want to proceed?"

**Comment by cronoh** [comment]
I agree with you @jcraigk - a bigger confirmation is in store.  I will add this to the list and update here when it is ready.  Thanks!

**Comment by cronoh** [comment]
This option has now been added in - you will receive a popup and have to confirm before creating/importing a wallet when one is already set up.  It is available now on the web wallet, and in the desktop wallet version 1.1.3 (Releasing shortly).  Let me know if any changes need to be made!
