### ISSUE TITLE
Set Default Rep for New Accounts

### ISSUE THREAD

**Issue by jmmcgee** [cronoh/nanovault#65]
This feature was suggested in #32 which was closed b/c support for changing accounts reps easily and in aggregate was added (if I understood correctly).

Though I've been unable to set a default rep for new accounts (open blocks). Rather a hard-coded default seems to be used for open blocks, requiring me to then change the rep afterwards. Problems:

- This is an incovnenience which shouldn't be too difficult to fix.
- Always defaulting to a particular rep or set of reps for the open block can be used as the basis for analysis to determine which accounts correspond to a particular service. Since nanovault is the only wallet that supports a hw wallet (the ledger nano s), this analysis could be extended to identify relatively high-value accounts residing on ledgers. I don't think this is particularly likely analysis or useful, but it could be easily nerfed by allowing users to specify what rep should be assigned in the open block.
- The same default rep is set even when I unmark that rep as 'Trusted', mark it as 'Avoid', or if the rep is 'offline'. It should be clear that it doesn't make sense to set a rep even momentarily that isn't trusted, one wants to actively avoid, or is offline.

I don't think this is a particularly important feature, but it'd be nice if you got around to it. I don't think there's any issue with setting a default default rep for new accounts, but users should be able to configure that away *before* any block hits the network.

**Comment by cronoh** [comment]
@jmmcgee Thank you for the detailed report.  You are correct that the open block is hard set to the NanoVault representative, and I agree with your reasoning for making that adjustable.  I will add this into the list and update you here when I have added the option in.  Thanks!

**Comment by BitDesert** [comment]
I would recommend the following:
- Use either a representatives array with reps you trust or implement a external service like My Nano Ninja with the scoring system
- Maybe an option to set your own default rep

**Comment by cronoh** [comment]
For now I have added in the option to set your own default rep, which is available on the web wallet.  I will also add in the integration with My Nano Ninja's list soon, which should work fine with this feature.  I am going to close this issue for now, but a new issue can be opened for adding in the My Nano Ninja integration.
