### ISSUE TITLE
nano issue using a ledger nano s with 

### ISSUE THREAD

**Issue by Airtool63** [cronoh/nanovault#66]
Hello There,
I recently used my ledger nano s to receive some additional coins from an exchange.  My ledger has the latest software and used the nano vault web wallet in conjunction with my ledger. 

I did experience an "Unpocketed Transaction" with this transfer.  Was able to learn how to rectify, which I had done successfully.

On Nanode.co the wallet address displays the correct amount,  but when using the latest desktop version or the web wallet.  Balance states zero. 
Please advise, thanks in advance

**Comment by cronoh** [comment]
We were recently experiencing some issues with our node server @Airtool63 - please try and reload the page now and let me know if the issues still persist.

**Comment by Airtool63** [comment]
All Good!

Thanks Andrew

**Comment by schonthal** [comment]
Similar experience. I transferred my nano from Binance to my Nanovault account via Ledger x two weeks ago and today it still says pending deposit with an account balance of 0.
Please help.
