### ISSUE TITLE
Mac close issue.

### ISSUE THREAD

**Issue by turrgavi** [cronoh/nanovault#7]
There is no option to quit mac app. Need to force quit from taskbar.

**Comment by cronoh** [comment]
@turrgavi Thanks for the feedback,

You should be able to quit the app using the top bar after closing the window, or by right clicking it from the dock.  This is just a weird OSX standard, where apps stay launched without windows and clicking them from the dock restarts them. I can make it close the whole app when you close the initial window though, would that be preferred?

**Comment by termhn** [comment]
No, I think keeping by osx convention is much better.

**Comment by cronoh** [comment]
Thanks @termhn 

Anyone else have any feedback on this?  If not I will leave it defaulted to the OSX standard I think.

**Comment by giltotherescue** [comment]
I’d prefer the OSX standard for sure

**Comment by cronoh** [comment]
Okay thanks @giltotherescue

Going to leave it as the OSX standard for now.  I will re-open if there are more requests for this change.  Thanks for the feedback everyone.
