### ISSUE TITLE
Password I used last and made note of is not working ?

### ISSUE THREAD

**Issue by ptatigina** [cronoh/nanovault#71]
I have my seed and mnemonic still but the password I have last recorded is not working when I go to log into my nanovault account

**Comment by cronoh** [comment]
Hmm, I haven't received any reports of this before.  Is it possible that you did not open your NanoVault wallet for many months?  I have one idea in mind which could have caused it - but if you have used your wallet successfully within the last 30 days or so - it wouldn't apply.  Worst case, you can just import your seed again, and it will allow you to create a new password.  Let me know - thanks!
