### ISSUE TITLE
When clearing all locally stored data, the representative list is not reset

### ISSUE THREAD

**Issue by catenocrypt** [cronoh/nanovault#72]
Reproduction:
- app settings, clear ALL data
- start with empty state
- check representative list (Manage Representatives): contains the default list
- remove all items (one by one)
- app settings, clear ALL data
- check representative list: empty
Proposed expected behavior: should be again the default list.

**Comment by catenocrypt** [comment]
Solution is available in this PR:
https://github.com/cronoh/nanovault/pull/73

**Comment by cronoh** [comment]
PR has been merged in and will be ready with the next deploy.  I will close this issue once it is deployed.  Thank you @catenocrypt

**Comment by cronoh** [comment]
This has now been deployed to the web wallet.  It will go to desktop in the next version.  Thanks again @catenocrypt
