### ISSUE TITLE
Pending transaction

### ISSUE THREAD

**Issue by david-aguirre** [cronoh/nanovault#74]
I sent Nano from my Binance account to my NanoVault since 10-Apr-2019 and today 12-Apr-2019 the funds have not been confirmed. I get the message "Pending transaction". Can someone help with this please?
![Screen Shot 2019-04-12 at 5 17 33 PM](https://user-images.githubusercontent.com/49574880/56071856-77c8ee80-5d4e-11e9-8ef2-3e92d7cec43c.png)

**Comment by tombertrand** [comment]
I get the same issue, connected a ledger nano s, opened the app and the transaction is still pending I can't see a way to send the receive block. Also when I try to send nano with the same ledger connected I get the confirmation screen and accept but nothing happens, the Nano are not sent.

**Comment by EchoZeroJ** [comment]
I've got the same problem. Still Pending since 6 hours ago...

**Comment by david-aguirre** [comment]
I found a way around it, since support here seems to be non-existent... Just import your funds to a different wallet with your seed. It worked for me at least.

**Comment by Eothred** [comment]
I seem to have the same issue, also a Ledger Nano S user. I have pending transactions for one month soon (no rush so haven't bothered to look further). I don't find a button anywhere to trigger receives

**Comment by divinationstar** [comment]
> I seem to have the same issue, also a Ledger Nano S user. I have pending transactions for one month soon (no rush so haven't bothered to look further). I don't find a button anywhere to trigger receives

The fix is to go directly to nanovault.io/receive URL. Then you will see your pending transaction(s) and can click to complete them. In Chrome browser.

**Comment by cronoh** [comment]
Please reply here or create a new issue if you are still having problems.
