### ISSUE TITLE
QR code on Account details page should go directly to the pre-filled Send page

### ISSUE THREAD

**Issue by catenocrypt** [cronoh/nanovault#76]
The QR code on the account page currently encodes the accountID only.
It would be very handy if it would encode a full URL to a nanovault send page with the target account ID prefilled (e.g. https://nanovault.io/send?to=xrb_aaa; the send route supports prefill of target account!).
If the user has a mobile phone with nanovault already configured, all she has to do is scan the QR code (with an external QR code reader app), open the link, and it will open up the send page with a default source account (from the configured wallet), and filled target account.  Only sum has to be entered and the send can be initiated.

**Comment by catenocrypt** [comment]
I provide two possible solutions:
- always use full nanovault URL -- a simpler solution -- PR #77 ;
- QR code style configurable -- a complete solution -- PR #78 ;

**Comment by catenocrypt** [comment]
Sample screenshots:

![image](https://user-images.githubusercontent.com/13562139/56194276-e64dcb00-6032-11e9-966d-b3faec2d1bbe.png)

![image](https://user-images.githubusercontent.com/13562139/56194344-0c736b00-6033-11e9-90c5-358a409943c8.png)

**Comment by optout21** [comment]
Closing after 3+ years
