### ISSUE TITLE
QR code scanning from within the app

### ISSUE THREAD

**Issue by catenocrypt** [cronoh/nanovault#79]
Nanovault displays QR codes, as do other Nano wallet implementations as well.  However, scanning a QR code requires an external applicaiton (e.g. on  mobile).
It would be nice if QR scanning can be done right from within the web app.  This is possible with client-side QR code scanning libraries.  It would be most useful on mobile phone devices, but works on laptops as well.
I can provide a working implementation (based on the InstaScan library).

**Comment by catenocrypt** [comment]
Note: this has been done in https://wallet.mikron.io  https://github.com/mikroncoin/mikron-vault-web/issues/10

**Comment by catenocrypt** [comment]
Working implementation is here:  PR #80  .

Screenshot:
![Screenshot from 2019-05-10 10-55-49](https://user-images.githubusercontent.com/13562139/57515525-2727bf80-7313-11e9-9f11-89045847c7c0.png)

**Comment by optout21** [comment]
Closing after 3+ years.
