### ISSUE TITLE
Scanning qr code with mobile wallet adds 'xrb:' in front of xrb address 

### ISSUE THREAD

**Issue by egonm12** [cronoh/nanovault#8]
## How to reproduce?

1. Install the Android mobile wallet
2. Click the 'send' button to go to the send view in the app
3. Click the camera in the right top corner
4. Scan the QR Code from your address in the Nanovault desktop app (Windows)

## Problem
As you can you see it adds the `xrb:` in front of the address and leaves the last 4 characters of the address out.
When I scan the QR Code from the official desktop wallet (beta) or from nanowallet.io it adds the address correctly so I assume it's a bug inside nanovault 

![screenshot_20180222-213729](https://user-images.githubusercontent.com/20042349/36562899-ae127460-1818-11e8-8680-37f483891d95.jpg)

**Comment by tanoabeleyra** [comment]
This is not the repo of the official app. This is for NanoVault.

**Comment by termhn** [comment]
> This is not the repo of the official app. This is for NanoVault.

I think he knows that, he specifically says

> When I scan the QR Code from the official desktop wallet (beta) or from nanowallet.io it adds the address correctly so I assume it's a bug inside nanovault

**Comment by cronoh** [comment]
Thanks for reporting this, I was following the official standard laid out here https://github.com/nanocurrency/raiblocks/wiki/URI-and-QR-Code-Standard - but maybe they are not following that in the official app.  I will change it and update this when it is live.

**Comment by cronoh** [comment]
@egonm12 This should now be fixed in https://github.com/cronoh/nanovault/commit/bdb1e3795b9dbb3b08635aac7796b49c0572bd5c - please let me know if you have any issues!

**Comment by egonm12** [comment]
@cronoh Easy fix and it's working correctly now 👍 Maybe contact the devs of nano so the docs are updated
